workflows:
  android-workflow:
    name: Android Release
    instance_type: mac_mini_m1
    working_directory: app
    environment:
      groups:
        - Default
      flutter: 3.27.2
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Set up keystore
        script: |
          echo $KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
          cp $CM_BUILD_DIR/keystore.jks android/app/keystore.jks
      - name: Set up key.properties
        script: |
          cat >> android/key.properties << EOF
          storeFile=keystore.jks
          storePassword=$STORE_PASSWORD
          keyAlias=$KEY_ALIAS
          keyPassword=$KEY_PASSWORD
          EOF
      - name: Build AAB
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
        changes_not_sent_for_review: true