workflows:
  android-workflow:
    name: Android Release
    instance_type: mac_mini_m1
    working_directory: src
    environment:
      groups:
        - Default
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
      flutter: 3.27.2
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > android/local.properties
      - name: Clean and Get Packages
        script: |
          flutter clean
          flutter pub get
      - name: Set up keystore
        script: |
          echo $KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
          cp $CM_BUILD_DIR/keystore.jks android/app/keystore.jks
      - name: Set up key.properties
        script: |
          cat >> android/key.properties << EOF
          storeFile=keystore.jks
          storePassword=$STORE_PASSWORD
          keyAlias=$KEY_ALIAS
          keyPassword=$KEY_PASSWORD
          EOF
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Build AAB
        script: |
          cd android
          ./gradlew clean
          cd ..
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.pub-cache