name: alphareader
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.10+11

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  meta: ^1.15.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  carousel_slider: ^5.0.0
  file_picker: ^10.1.2
  archive: ^4.0.7
  path_provider: ^2.1.5
  html: ^0.15.5+1
  flutter_widget_from_html: ^0.16.0
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.4.1
  uuid: ^4.5.1
  freezed_annotation: ^2.0.1 
  purchases_flutter: ^8.7.3
  google_mobile_ads: ^6.0.0
  path: ^1.9.0
  permission_handler: ^12.0.0+1
  worker_manager: ^7.2.3
  shared_preferences_android: ^2.4.10
  shared_preferences_ios: ^2.1.1
  fb2_parse:
    git:
      url: https://github.com/Alienjob/fb2_parse
      ref: 0e60b27
      
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15
  freezed: ^2.0.1 

flutter:
  uses-material-design: true

